export interface Bike {
    brand: string;
    model: string;
    engine_capacity: string;
    color: string;
    year: number;
    fuel_type: string;
    rental_price_per_day: number;
    availability: boolean;
    mileage: string;
    transmission: string;
    location: string;
    insurance_included: boolean;
    number_of_seats: number;
    license_requirement: string;
    additional_features: string[];
    bike_image: string;
}


export const bikes: Bike[] = [
    {
        brand: "Yamaha",
        model: "R15",
        engine_capacity: "150cc",
        color: "Blue",
        year: 2022,
        fuel_type: "Petrol",
        rental_price_per_day: 50,
        availability: true,
        mileage: "45 kmpl",
        transmission: "Manual",
        location: "Fujairah, UAE",
        insurance_included: true,
        number_of_seats: 2,
        license_requirement: "Motorcycle License",
        additional_features: ["ABS", "Tubeless Tires"],
        bike_image: "https://example.com/images/yamaha_r15_blue.jpg"
    },
    {
        brand: "Honda",
        model: "CBR150R",
        engine_capacity: "150cc",
        color: "Red",
        year: 2021,
        fuel_type: "Petrol",
        rental_price_per_day: 55,
        availability: false,
        mileage: "40 kmpl",
        transmission: "Manual",
        location: "Dubai, UAE",
        insurance_included: true,
        number_of_seats: 2,
        license_requirement: "Motorcycle License",
        additional_features: ["ABS", "LED Lights"],
        bike_image: "https://example.com/images/honda_cbr150r_red.jpg"
    },
    {
        brand: "Suzuki",
        model: "GSX-R150",
        engine_capacity: "150cc",
        color: "Black",
        year: 2023,
        fuel_type: "Petrol",
        rental_price_per_day: 60,
        availability: true,
        mileage: "50 kmpl",
        transmission: "Manual",
        location: "Abu Dhabi, UAE",
        insurance_included: true,
        number_of_seats: 2,
        license_requirement: "Motorcycle License",
        additional_features: ["Tubeless Tires", "Digital Meter"],
        bike_image: "https://example.com/images/suzuki_gsx_r150_black.jpg"
    },
    {
        brand: "Kawasaki",
        model: "Ninja 300",
        engine_capacity: "300cc",
        color: "Green",
        year: 2020,
        fuel_type: "Petrol",
        rental_price_per_day: 80,
        availability: true,
        mileage: "35 kmpl",
        transmission: "Manual",
        location: "Sharjah, UAE",
        insurance_included: true,
        number_of_seats: 2,
        license_requirement: "Motorcycle License",
        additional_features: ["ABS", "LED Headlights"],
        bike_image: "https://example.com/images/kawasaki_ninja_300_green.jpg"
    },
    {
        brand: "Yamaha",
        model: "MT-15",
        engine_capacity: "150cc",
        color: "Gray",
        year: 2023,
        fuel_type: "Petrol",
        rental_price_per_day: 55,
        availability: true,
        mileage: "48 kmpl",
        transmission: "Manual",
        location: "Fujairah, UAE",
        insurance_included: true,
        number_of_seats: 2,
        license_requirement: "Motorcycle License",
        additional_features: ["LED Lights", "Digital Meter"],
        bike_image: "https://example.com/images/yamaha_mt15_gray.jpg"
    },
    {
        brand: "Honda",
        model: "CBR250RR",
        engine_capacity: "250cc",
        color: "Black",
        year: 2022,
        fuel_type: "Petrol",
        rental_price_per_day: 75,
        availability: true,
        mileage: "40 kmpl",
        transmission: "Manual",
        location: "Dubai, UAE",
        insurance_included: true,
        number_of_seats: 2,
        license_requirement: "Motorcycle License",
        additional_features: ["ABS", "Slipper Clutch"],
        bike_image: "https://example.com/images/honda_cbr250rr_black.jpg"
    },
    {
        brand: "Suzuki",
        model: "Gixxer SF 250",
        engine_capacity: "250cc",
        color: "Silver",
        year: 2021,
        fuel_type: "Petrol",
        rental_price_per_day: 70,
        availability: true,
        mileage: "38 kmpl",
        transmission: "Manual",
        location: "Abu Dhabi, UAE",
        insurance_included: true,
        number_of_seats: 2,
        license_requirement: "Motorcycle License",
        additional_features: ["LED Headlights", "Tubeless Tires"],
        bike_image: "https://example.com/images/suzuki_gixxer_sf_250_silver.jpg"
    },
    {
        brand: "Kawasaki",
        model: "Z650",
        engine_capacity: "650cc",
        color: "Black",
        year: 2021,
        fuel_type: "Petrol",
        rental_price_per_day: 90,
        availability: true,
        mileage: "30 kmpl",
        transmission: "Manual",
        location: "Sharjah, UAE",
        insurance_included: true,
        number_of_seats: 2,
        license_requirement: "Motorcycle License",
        additional_features: ["ABS", "Traction Control"],
        bike_image: "https://example.com/images/kawasaki_z650_black.jpg"
    },
    {
        brand: "Yamaha",
        model: "YZF-R3",
        engine_capacity: "300cc",
        color: "Blue",
        year: 2020,
        fuel_type: "Petrol",
        rental_price_per_day: 85,
        availability: true,
        mileage: "35 kmpl",
        transmission: "Manual",
        location: "Fujairah, UAE",
        insurance_included: true,
        number_of_seats: 2,
        license_requirement: "Motorcycle License",
        additional_features: ["ABS", "LED Headlights"],
        bike_image: "https://example.com/images/yamaha_r3_blue.jpg"
    },
    {
        brand: "Honda",
        model: "CB500X",
        engine_capacity: "500cc",
        color: "Red",
        year: 2021,
        fuel_type: "Petrol",
        rental_price_per_day: 100,
        availability: true,
        mileage: "30 kmpl",
        transmission: "Manual",
        location: "Dubai, UAE",
        insurance_included: true,
        number_of_seats: 2,
        license_requirement: "Motorcycle License",
        additional_features: ["ABS", "Traction Control"],
        bike_image: "https://example.com/images/honda_cb500x_red.jpg"
    },
    {
        brand: "Suzuki",
        model: "V-Strom 650",
        engine_capacity: "650cc",
        color: "Yellow",
        year: 2021,
        fuel_type: "Petrol",
        rental_price_per_day: 95,
        availability: true,
        mileage: "30 kmpl",
        transmission: "Manual",
        location: "Abu Dhabi, UAE",
        insurance_included: true,
        number_of_seats: 2,
        license_requirement: "Motorcycle License",
        additional_features: ["ABS", "Traction Control"],
        bike_image: "https://example.com/images/suzuki_vstrom_650_yellow.jpg"
    },
    {
        brand: "Kawasaki",
        model: "Versys 650",
        engine_capacity: "650cc",
        color: "Green",
        year: 2020,
        fuel_type: "Petrol",
        rental_price_per_day: 90,
        availability: true,
        mileage: "28 kmpl",
        transmission: "Manual",
        location: "Sharjah, UAE",
        insurance_included: true,
        number_of_seats: 2,
        license_requirement: "Motorcycle License",
        additional_features: ["ABS", "Slipper Clutch"],
        bike_image: "https://example.com/images/kawasaki_versys_650_green.jpg"
    },
    {
        brand: "Yamaha",
        model: "MT-09",
        engine_capacity: "900cc",
        color: "Gray",
        year: 2022,
        fuel_type: "Petrol",
        rental_price_per_day: 120,
        availability: true,
        mileage: "25 kmpl",
        transmission: "Manual",
        location: "Fujairah, UAE",
        insurance_included: true,
        number_of_seats: 2,
        license_requirement: "Motorcycle License",
        additional_features: ["ABS", "Traction Control"],
        bike_image: "https://example.com/images/yamaha_mt09_gray.jpg"
    },
    {
        brand: "Honda",
        model: "Africa Twin",
        engine_capacity: "1000cc",
        color: "White",
        year: 2021,
        fuel_type: "Petrol",
        rental_price_per_day: 150,
        availability: true,
        mileage: "20 kmpl",
        transmission: "Manual",
        location: "Dubai, UAE",
        insurance_included: true,
        number_of_seats: 2,
        license_requirement: "Motorcycle License",
        additional_features: ["ABS", "Traction Control"],
        bike_image: "https://example.com/images/honda_africa_twin_white.jpg"
    }
];
